---
title: "Most occuring words in headlines"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Shiny dashboard which displays words which occur most frequently in newspaper headlines

Using this dashboard,you can find out words mostly used across newspapers in different countries on a particular date.Also there is an option to filter between the newspaper formats such as tabloid and broadsheet.

```{r message = FALSE, warning = FALSE, include = FALSE}
# importing csv files -----------------------------------------------------
file_paths <- fs::dir_ls("data")
file_paths

file_contents <- list()

for (i in seq_along(file_paths)) {
  file_contents[[i]] <- read_csv(
    file = file_paths[[i]]
  )
}

file_contents <- set_names(file_contents, file_paths)

headlines <- do.call(rbind, file_contents)
```

```{r message = FALSE, warning = FALSE, include = FALSE}
# cleaning with function - before tokenizing! --------------------------------------------------

clean_data <- function(x) { # x = path
  df <- x
  df$time <- as.POSIXct(df$time) %>% as.character() %>% str_replace_all("[ :]", "-")
  df <- select(df, -"...1")
  df$value <- gsub("<.*?>", "", df$value) # remove html tages
  df$value <- gsub(' +',' ', df$value) # remove more than one space
  df$value <- str_trim(df$value, side = c("both", "left", "right")) # remove spaces at start and end
  df[df == ""] <- NA #adding NAs to blank cells
  df <- na.omit(df) # remove NAs
  df <- rename(df, headline = value)
}

headlines <- clean_data(headlines)
```

```{r message = FALSE, warning = FALSE, include = FALSE}
headlines <- headlines %>% # maximum of 5500 headlines to avoid distortion, escecially of uk newspaper dailymail
  mutate(country = dplyr::case_when(name == "guardian" ~ "UK",
                                    name == "times" ~ "UK",
                                    name == "dailymail" ~ "UK",
                                    name == "independent" ~ "UK",
                                    name == "mirror" ~ "UK",
                                    name == "telegraph" ~ "UK",
                                    name == "nytimes" ~ "US",
                                    name == "wsj" ~ "US",
                                    name == "usatoday" ~ "US",
                                    name == "washingtonpost" ~ "US",
                                    name == "latimes" ~ "US",
                                    name == "tampabay" ~ "US",
                                    name == "heraldsun" ~ "Australia",
                                    name == "dailytelegraph" ~ "Australia",
                                    name == "financialreview" ~ "Australia",
                                    name == "couriermail" ~ "Australia",
                                    name == "westaustralian" ~ "Australia",
                                    name == "advertiser" ~ "Australia",
                                    name == "globeandmail" ~ "Canada",
                                    name == "thestar" ~ "Canada",
                                    name == "nationalpost" ~ "Canada",
                                    name == "torontosun" ~ "Canada",
                                    name == "vancouversun" ~ "Canada",
                                    name == "montrealgazette" ~ "Canada",
                                    name == "nzherald" ~ "New-Zealand",
                                    name == "waikato" ~ "New-Zealand",
                                    name == "businessreview" ~ "New-Zealand",
                                    name == "gisborneherald" ~ "New-Zealand",
                                    name == "dominionpost" ~ "New-Zealand",
                                    name == "thepress" ~ "New-Zealand"),
         
          format = dplyr::case_when(name == "dailymail" ~ "tabloid",
                                    name == "mirror" ~ "tabloid",
                                    name == "couriermail" ~ "tabloid",
                                    name == "westaustralian" ~ "tabloid",
                                    name == "advertiser" ~ "tabloid",
                                    name == "torontosun" ~ "tabloid",
                                    name == "nzherald" ~ "tabloid",
                                    TRUE ~ "broadsheet"),
         
         day = dplyr::case_when(grepl("2021-12-09", time) ~ "December 9",
                                grepl("2021-12-10", time) ~ "December 10",
                                grepl("2021-12-11", time) ~ "December 11",
                                grepl("2021-12-12", time) ~ "December 12",
                                grepl("2021-12-13", time) ~ "December 13",
                                grepl("2021-12-14", time) ~ "December 14",
                                grepl("2021-12-15", time) ~ "December 15",
                                grepl("2021-12-16", time) ~ "December 16"))

```

```{r message = FALSE, warning = FALSE, include = FALSE}
# ensuring balance --------------------------------------------------------
headlines <- headlines %>% 
  group_by(name) %>% 
  slice(1:5000) %>% 
  ungroup()

# tokenizing --------------------------------------------------------------
headlines_tok <- headlines %>% 
  unnest_tokens(output = word, input = headline) %>% 
  anti_join(stop_words) 
# clean -------------------------------------------------------------------

headlines_tok <- headlines_tok %>% 
  filter(!grepl('content|subscriber|read|star|10|9|6|min|l.a|wa|nz|canada|uk|west|tampa|times|2021|2022|home|life
                |time|top|city|day|people|world|house|win|reveals|revealed|dont|1|amid|live', word))  # dailymail uses the word star everywhere



Number <-1



headlines_tok["Number"] <- Number #adding a new column to help count


```

## Code for the dashboard


```{r}

library(shiny)
library(shinydashboard)

# headlines_tok <- headlines_tok[headlines_tok, drop = FALSE]

ui <- dashboardPage(
    dashboardHeader(title = "Words in Headlines"),
    
    dashboardSidebar(
        sidebarMenu(
            menuItem("Most occuring words",
                     tabName = "Most_occuring_words",
                     icon = icon("dashboard"))
        )
    ),
    
    dashboardBody(
        tabItems(
            tabItem(tabName = "Most_occuring_words",
                    fluidRow(column(# width should be between 1 and 12
               width=6,
               box(plotly::plotlyOutput("plot1"), 
                   title="Most Common Words Across Newspapers", numericInput(inputId = "select_topn",
                                label = "Select number of words to display", 
                                  value = 5,min = 3, max = 15, step=1),
                   # For column based layouts, we can set box width to NULL
                   # This overrides the default value
                   width=NULL)
              )
              ,column(# width should be between 1 and 12
                width=6,
               box(dataTableOutput("table1"),
                   title="Most Common Words Across used in Newspapers across countries",
                    # For column based layouts, we can set box width to NULL
                    # This overrides the default value
                    width=NULL)
               ),box(uiOutput("name")), box(uiOutput("day"))),
                    box(uiOutput("country")),box(uiOutput("format"))
                    )
        )
    )
    
    
)


server <- function(input, output) {  
  
  output$country <- renderUI({
        
        
        selectInput(inputId = "country",
                    label = "Country",
                    choices = headlines_tok %>% 
                        select(country) %>% 
                        distinct() %>% 
                        arrange(country))
    })
  
    output$day <- renderUI({
        
        days_selector_df <- headlines_tok %>% 
            select(day) %>%  
            distinct() 
        
        
      days_selector_df2 <- days_selector_df[order(substr(days_selector_df,10,12))]
        
        
        selectInput(inputId = "day",
                    label = "Days",
                    choices = days_selector_df2)
    })
    
    output$format <- renderUI({
        
  format_df <- headlines_tok %>% 
            select(format) %>%  
            distinct() %>% 
            arrange(format)
        
        selectInput(inputId = "format",
                    label = "Format",
                    format_df)
    })
    
    
    
     # headlines_tok %>% filter(country == "US" & day == "December 9" & format == "tabloid" ) %>%  select(name) %>%  
     #        arrange(name)%>% 
     #        distinct()
    
    output$name <- renderUI({
      
      name_df <- headlines_tok %>% filter(country == input$country & day ==input$day & format ==input$format ) %>% 
            select(name) %>%  
            arrange(name)%>% 
            distinct() 
      
      
        
        selectInput(inputId = "name",
                    label = "Newspaper",
                    choices = name_df)
        
        
    })
    
# headlines <- headlines_tok %>% filter(country == input$country & day ==input$day & format ==input$format & name ==input$name) %>% group_by(word) %>% 
#        summarise(occurrences=sum(Number)) %>% 
#      arrange(desc(occurrences)) %>% 
#       top_n(input$select_topn) %>%
#       ungroup()
#     
# headlines$word <- factor(headlines$word, levels = headlines$word[order(headlines$occurrences)])

output$plot1 <- plotly::renderPlotly({
     plotly::ggplotly(headlines_tok %>% filter(country == input$country & day ==input$day & format ==input$format & name ==input$name) %>% group_by(word) %>% 
       summarise(occurrences=sum(Number)) %>% 
     arrange(desc(occurrences)) %>% 
      top_n(input$select_topn) %>%
      ungroup()
      %>% 
    ggplot(aes(x=reorder(word,occurrences), 
               y=occurrences)) +
    geom_col() +
    ## Bonus: uncomment to make some aesthetic changes or add your own
    ylab("count") +
      xlab("word")+
    coord_flip() +
     theme_minimal() +
   scale_fill_gradient(high = "#f6a97a", low="#ca3c97") +
     ggtitle(paste("Top", input$select_topn , "frequently used words")) + 
     geom_blank()
   )
   })
   
   output$table1 <- renderDataTable({
     headlines_tok %>% filter(country == input$country & day ==input$day & format ==input$format & name ==input$name) %>%
     group_by(word) %>% 
   summarise(occurrences=sum(Number)) %>% 
    arrange(desc(occurrences)) %>% 
    top_n(input$select_topn) %>%
    ungroup()
   })
}

shinyApp(ui, server)


```



